### ISSUE TITLE
Registration and Moderator Selection Page

### ISSUE THREAD

**Issue by shubhanshu02** [shubhanshu02/InstiComplaints-App#8]
The registration page takes the basic user info as input to register the user on the app. The moderator selection page (for admin only) provides the option to select a moderator from the students or remove the moderator. Assigned to @shubhanshu02

**Comment by shubhanshu02** [comment]
Below is my proposal for the registration page.
![Registration Proposal](https://user-images.githubusercontent.com/54344426/91175725-db16af00-e6fe-11ea-96b1-76304ac98f98.png)

**Comment by Kenny-08** [comment]
That purple color of submit button is not going well with the rest of the page... you can change it to either yellow-orange color of logo or dark blue of top! Rest everything is fine.

**Comment by shubhanshu02** [comment]
The following are the designs after including the suggested changes -
<img width="162" alt="Yellow Button" src="https://user-images.githubusercontent.com/54344426/91186067-3602d300-e70c-11ea-9ee2-dcc17ac61909.png">
<img width="162" alt="Blue Button" src="https://user-images.githubusercontent.com/54344426/91186074-37cc9680-e70c-11ea-8e3e-9bc407dfcbb6.png">

**Comment by jainsid2305** [comment]
I think that this one with Yellow submit Button is looking better.
<img width="162" alt="91186067-3602d300-e70c-11ea-9ee2-dcc17ac61909" src="https://user-images.githubusercontent.com/59123466/91193422-b62d3680-e714-11ea-9234-7238cd54d866.png">

**Comment by shubhanshu02** [comment]
Closing this issue with pull #10
